server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # A linha abaixo resolve o problema do F5 (Refresh) no React/Vite
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos para ficar ultrarrápido
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
